### ISSUE TITLE
[Bug] Annoying log spam

### ISSUE THREAD

**Issue by aGingerThing** [Aton-Kish/quartz-elevator#2]
### Describe the bug

Every time someone uses an elevator I get a warning saying"Player moved too quickly!"

### To Reproduce

1. run a server with the mod
2. use an elevator

### Expected behavior

no warning every time someone uses an elevator

### Environment

- Minecraft: [e.g. 1.16.5]
- Fabric Loader: [e.g. 0.11.1]
- Fabric API: [e.g. 0.29.4+1.16]

### Logs

Pastebin the log [e.g. `logs/latest.log`] and link it below:

https://paste.ubuntu.com/p/2NWBKJjGX9/<!-- ```log

### Additional context

it isn't really that bad it is just annoying when someone goes up and down the elevators and it spams my server log

**Comment by Aton-Kish** [comment]
Thank you for reporting.
In version 1.2.1, I couldn't completely erase the annoying logs, but I think they are reduced.
<https://www.curseforge.com/minecraft/mc-mods/quartz-elevator/files>

**Comment by aGingerThing** [comment]
oh ok I'll try that out.

**Comment by Aton-Kish** [comment]
Close this issue because  it has been open for a long time with no updates.
Feel free to restore and update if you wish to continue working on this.
