### ISSUE TITLE
[Bug] Can't go up when elevator is below y:0

### ISSUE THREAD

**Issue by mrsolarius** [Aton-Kish/quartz-elevator#27]
### Describe the bug
When I place an elevator under the y:0 coordinate, I can only get down

### To Reproduce
1. Install quartz elevator on 1.17 version with fabric
2. Place two elevators, one above y:0 and the other below y:0 with a minimum 16 blocks of height between.
3. Try to jump when you are on the below y:0 and discover that you can't jump above

### Expected behavior
I expect to go up when I jump when the elevator is below y:0

### Environment
- Minecraft: 1.17.0
- Fabric Loader: 0.11.6
- Fabric API: 0.36.0+1.17

### Logs
Don't know where to find logs

### Additional context
I have found this bug with the mode pack  [Better Minecraft](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric)

**Comment by mrsolarius** [comment]
Fixed in 99f183bac56b4165d8a262f924533e6252a99d24
I just do not have updated the mod sorry ^^'

**Comment by Aton-Kish** [comment]
Thank you for playing with my mod.
I'm glad you could solve this issue!
