### ISSUE TITLE
[Feature] Korean Translation

### ISSUE THREAD

**Issue by gyular** [Aton-Kish/quartz-elevator#30]
if you fine, add korean translation please.
https://gist.github.com/gyular/dbffae0e7d2ee32ab0aebb0a9f8286cb

**Comment by Aton-Kish** [comment]
I'll take care of this tomorrow.

**Comment by Aton-Kish** [comment]
In version 2.0,1 for Minecraft 1.18 and 1.2.6 for Minecraft 1.17, added Korean translation.
<https://www.curseforge.com/minecraft/mc-mods/quartz-elevator>
