### ISSUE TITLE
Elevator blocks disappeared when logging on server [Bug]

### ISSUE THREAD

**Issue by lxrdjuni** [Aton-Kish/quartz-elevator#36]
### Describe the bug
I got on my server today and noticed all my elevator blocks were just gone, I checked a backup in my world in singleplayer and they are still there

### To Reproduce
not sure

1. First step ...
2. Second step ...

### Environment

- Minecraft: [e.g. 1.16.5]
- Fabric Loader: [e.g. 0.11.1]
- Fabric API: [e.g. 0.29.4+1.16]

### Logs

Pastebin the log [e.g. `logs/latest.log`] and link it below:

<!-- ```log
or paste the raw log here.
``` -->

### Additional context

Add any other context about the problem here.

**Comment by Aton-Kish** [comment]
I don't know from the information provided, but there should be some clues in the log from the time you backed up your world to this issue occurred.
So please check it.

**Comment by Aton-Kish** [comment]
If necessary, you can re-open this.
