### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by a-a3458** [Aton-Kish/quartz-elevator#39]
### Describe the bug
putting in custom values for max distance does not work in 1.18.2
custom values for max distance does not work for 1.18.2
### To Reproduce

1. First step ...use mod menu and hit configure 
2. Second step ... put in custom vlaue

### Expected behavior
for it to teleport me to the second elvator with custom vlaues
i expected it to telport me to the second elevator
### Environment

- Minecraft: [e.g. 1.18.2]
- Fabric Loader: [e.g. 0.11.1]
- Fabric API: [e.g. fabric-api-0.51.1+1.18.2.jar6]

### Logs

Pastebin the log [e.g. `logs/latest.log`] and link it below:

<!-- ```log
or paste the raw log here.
``` -->

### Additional context
I tested in a single player with default values that works but custom ones dont
Add any other context about the problem here.

**Comment by Aton-Kish** [comment]
I tried setting a custom distance (e.g. 384), and it worked well.
(I tried it with fabric loader 0.11.1, but it didn't launch well, so I did with the latest 0.13.3.)

- Minecraft: 1.18.2
- Fabric Loader: 0.13.3 (**NOT 0.11.1**)
- Fabric API: [fabric-api-0.51.1+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3759491)
- Quartz Elevator: [quartz-elevator-2.1.1+1.18.jar](https://www.curseforge.com/minecraft/mc-mods/quartz-elevator/files/3670913)

Please check if the custom values are set correctly.
If you still have a problem, you can re-open it.
