### ISSUE TITLE
[Bug] blocks have no effective tool

### ISSUE THREAD

**Issue by milkev** [Aton-Kish/quartz-elevator#5]
### Describe the bug

neither the quartz or smooth quartz elevator have effective tools and are thus not re-obtainable via mining them

### To Reproduce

1. place an elevator
2. attempt to mine it
3. be sad

### Expected behavior

elevators effective tool is a pickaxe, and they drop when they are mined

### Environment

- Minecraft: 1.17
- Fabric Loader: 0.11.6
- Fabric API: 0.35.2

### Additional context

Blockus had the same issue with multiple blocks, and this is likely the same thing

**Comment by Aton-Kish** [comment]
Thank you for reporting, I was able to fixed this issue in version 1.2.3.
<https://www.curseforge.com/minecraft/mc-mods/quartz-elevator/files>
